# Generated by Django 2.0.2 on 2018-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocksdetail',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'stocksdetail',
            },
        ),
        migrations.CreateModel(
            name='Stockslist',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('symbol', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('marketcap', models.FloatField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'stockslist',
            },
        ),
    ]
